### ISSUE TITLE
Windows version - installing this = selling your pc's soul

### ISSUE THREAD

**Issue by thecrazy** [Faster3ck/Converseen#13]
After using converseen in linux I was very happy with it but after seeing the joke you have made of the windows version...

The level of hypocrisy that went into trying to get them to install malware is staggering.

Skip all the malware install and nothing gets installed, converseen is nowhere to be found... then I tried the "portable" version without the addware (which you call software to support you...right) and thank god I passed it through virustotal... there is a virus in it.

You really dont give a shit about the trouble you cause others right?
Your program is very well made, if you want to earn money for it just sell it!
What do you make off of these stupid crapware installation anyways?
I bet you'd make more money with 24hours trial and sold activations keys for 0.50$ cents via paypal.

**Comment by Faster3ck** [comment]
As you can see in the download page for [**Converseen for Windows**](http://converseen.fasterland.net/download-for-windows/) there are different options to get the program on **Windows**:

* The standard version is a downloader with third party offers that user can skip. Many developers use third party offers to maintain active their project.

* Portable versions with third party offers and without. If you download the package with no ads and test it on VirusTotal it will be 100% clean because it's simply a compressed directory made with 7zip and it doesn't contain any third party software.

* The third option is **making a free donation**. As specified on the [download page](http://converseen.fasterland.net/download-for-windows/), users can make a one-time free donation via paypal and gain a life-time access to a **Contributor's Page** where they can download **all versions of the program including the complete windows installer without ads**.

Since no one makes free donations I think users prefer accepting or skipping ads instead of donating only 0.50 € so I think at the moment is useless to sell the program.
However I will consider this option for the future.

If you're interested on getting Converseen on Windows without third party apps you can download freely the portable package or making a free donation via Paypal as specified on the [download page](http://converseen.fasterland.net/download-for-windows/).

I'm sorry if you found me an hypocrite but I think I transparently specified on the download page every possible option to get the preferred version of my program with or without third party apps.

**Comment by thecrazy** [comment]
The downloader doesn't work, it says its complete but you cant find any file or executable for Converseen. Nothing gets installed. It does launch a website at the end but that turns out to be a white page. Tried with IE and Chrome on 2 pc.

As for the portable version **without** third party, what is **Trojan-Downloader.Win32.Small!cobra (v)** ?I suggest you head over to virus total.

I don't know what your original intents were but the way things are right now it doesn't look good for windows users and **seriously** I have **NEVER** seen so many adware stacked in a single installer. Not even ending with the software installed after all this... I bet if someone was to click next, next, next he would end up with all of the adwares installed, its not like you skip the rest once the user accepted one right?

As an IT guy I can only tell you this. I cannot recommend your software to Windows users. And I am going to have to monitor the linux version on my system, stuff could be hidden in there.

That been said, packaging a single addware or a search toolbar from google, yahoo or ask is something, but with the shady/poorly known stuff you are pushing... you are definitely not going to win over any self respecting IT guy.

**Comment by thecrazy** [comment]
FYI I do love your software though, and I find that it works very well, its just that the whole installation experience under window is scary as hell and does NOT promote trust, our first thought was: should I even try to run the clean version? What else may be happening underneath that we weren't told?

Anyway what do I know, over 15 years in the business, I'm probably just overreacting...

**Comment by tp0** [comment]
> If you download the package with no ads

Either there is a mistake on the download page or I am blind, because currently I can not find a link to the portable-no-ads version. There is a link to the exe bundle, but what kind of a portable version is that supposed to be?

> Since no one makes free donations

I can tell that at least in my case, instead of the Sourceforge crapware being sort of an incentive to donate, I am not going to donate because of it.

> but I think I transparently specified on the download page

I can't agree. Calling portable something that is an exe bundle is pretty confusing and hiding some of the links behind adfly etc does not help. For example the description of the options you just made on this page is much better.

**Comment by Faster3ck** [comment]
>The downloader doesn't work

I will test it asap in order to see if it works correctly.

> what is Trojan-Downloader.Win32.Small!cobra (v) ?

I have no idea of what is it. As I said before, the package is simply made using 7zip so I think it's a false positive. However, in order to remove every antivirus false positive problem I uploaded the portable version onto a 7z archive downloadable from the [download page](http://converseen.fasterland.net/download-for-windows/).

> things are right now it doesn't look good for windows users

I use this way to distribute this software from 2013 receiving about 2000 downloads for month and I received only 2-3 gripes since then so I think users prefer to accept or skip the third party apps.
Otherwise I offer the option to make a free donation to retrieve a life-time link to download the full installer but no one want to spend not even 1$.

> And I am going to have to monitor the linux version on my system, stuff could be hidden in there.

You can check the source code of **Converseen** [here](https://github.com/Faster3ck/Converseen) on **GitHub** and [here](https://sourceforge.net/projects/converseen/files/Converseen/Converseen%200.8/) on **SourceForge**. I suppose if it may hide some malware (I'd like to know why a software developer would hide something on it's publicly available source code) Linux packagers and users would have noticed that a long time ago.

> Anyway what do I know, over 15 years in the business, I'm probably just overreacting...

Unfortunately I think it may be frustrating downloading a Windows applications with third party apps, but it's the only realistic way to maintain a little software like this. Moreover I've always made available the portable version of the program without bundles apps sacrificing potential earnings because I would give to users the full freedom to choice what version of the sotware install.
No one wants to buy or donate money. This software was distributed without ads for 2 years before 2013 and I received only 3-4 little donations (1-5 euros) in a year.
The same for the self-styled righteous Linux users: everyone wants free stuff, everyone wants bugs solved at the speed of light, everyone want the right to lament when something doesn't works but I almost never receive donations (1 or 2 during 2014).
However I will try to follow your suggestion to sell it at low price and if I will earn enough to not let the software die I will remove the third party apps but honestly I don't think people want to buy anything.

> you are definitely not going to win over any self respecting IT guy

As you can see, I'm responding to you honestly and I'm not hiding anything. My only intent is simply creating useful software in my free time and earn something in order to pay web hosting and buy some books for university since studying costs a lot of money.

> I can not find a link to the portable-no-ads version

From now it's again available a 7z package for the portable version.

 > I am not going to donate because of it

The program has been freely available and with no ads for Linux, it was available for 2 years with no bundles app for Windows and I only received 3-4 donations on 5 years. 
This speak clearly: users are always ready to find an infinite reasons to not spending money.

> I can't agree. Calling portable something that is an exe bundle is pretty confusing and hiding some of the links behind adfly etc does not help

I think it's all explained well. I don't find anything illegal to use adfly to earn 0.00001$ from a simple click link. However I removed also this.

I hope I've explained myself clearly since english is not my native language.

**Comment by thecrazy** [comment]
For the downloader, once you skipped everything and finish the isntall, if your suposed to have the program installed something is definitly wrong cause I couldnt find anything anywhere and was never asked were to install the program.

Good call on removing the self extractable executable but I strongly suggest you change that 7z to zip unless once again you are traying to hide something. 7z cannot be inspected by every anti virus and other security software. Even if we all know 7z is technically better we all use zip for business.

As for your download vs complains... I think some people just browse by and dont even download when you mention the addware and you should know that most people will just move on and not complain so you cant rely on that. Especially if they dont have a github account allready.

For the business model, I think you would benifit way more by implementing adds somewere in your app. Its very common in free apps and it will work for you everytime someone uses your program. It may even be possible to put the add in a forced splash screen for 3 seconds on startup if you dont want to clutter the main interface. You could also include a some 3rd applications during install but man, dont make it possible for the user to install them by mistake, force them to make a choice, gray out the next button and just ask politely for people to help you finance the developement in the same screen. Make sure the apps you propose are not complete junk. Thats how you do it without pissing off people.

But truthfully, in a business, ads (from reputable ad networks) displayed on the screen are ok but usually when my team are looking for a new software, 3rd party apps often makes us look elsewere.

I think you can make a LOT more than 0.00001$ with ads and without scaring people a product that appears unclean. 

FYI the reason you are not getting any money is that you are not giving anyone a reason to and the only way to make that happen wihtout loosing rep is either with ads, locked features, or simply being the best out there but lets face it, another thing that doesnt help you is that there is a ton of picture converting programs out there, yours has the best design I have seen but it doesnt much further than the competition on features so if its scary to install, being well designed wont be enough.

Anyways, I have to give it to you that I you have been replying fast and owning this complain so +1 to you for that.

Take care, hope you can find a way around this bad vibe surrounding your current install process.
