### ISSUE TITLE
converseen 0.9.0 compilation error on Fedora rawhide (Feb/2014)

### ISSUE THREAD

**Issue by rosset** [Faster3ck/Converseen#14]
http://fpaste.org/188795/42457607/raw/

Do you have any idea what's happening?

ImageMagick-6.8.8.10-7.fc22.x86_64
ImageMagick-c++-6.8.8.10-7.fc22.x86_64
ImageMagick-c++-devel-6.8.8.10-7.fc22.x86_64
ImageMagick-devel-6.8.8.10-7.fc22.x86_64
ImageMagick-libs-6.8.8.10-7.fc22.x86_64

**Comment by Faster3ck** [comment]
I think the problem could be related to GCC 5 or some ImageMagick bug. I've just compiled Converseen on my Arch Linux with GCC 4.9.2 20150204 and ImageMagick 6.9.0.5 and works fine.
If the problem is related to GCC 5 I will release a patch if needed but at the moment I cannot test the program with GCC 5.

However you may try to compile the program using a newer version of ImageMagick and test if the program can be compiled correctly.

**Comment by mtasaka** [comment]
This means that (even if Fedora rawhide does not upgrade ImageMagick right now) at least rebuild of ImageMagick on Fedora rawhide (F-23) is needed, see:
http://developerblog.redhat.com/2015/02/10/gcc-5-in-fedora/

**Comment by rosset** [comment]
ImageMagick was updated on Fedora rawhide, so converseen 0.9.1 builds fine, I'm closing this issue, thank you.

**Comment by Faster3ck** [comment]
Thank you for the information :)
