### ISSUE TITLE
Build instructions for WIndows?

### ISSUE THREAD

**Issue by lduperval** [Faster3ck/Converseen#153]
HI,

This isn't an issue per se, I don't think. Are there build instructions for Windows? I loaded the sln file in Microsoft Visual Studio 2022 and I get a bunch of errors compiling the *ts files. I suspect there's something missing in my environment but I don't see what. Maybe I'm not supposed to be able to build it in Visual Studio?

**Comment by Faster3ck** [comment]
Hi, instructions for compiling Converseen on Windows are not present because it is a process that sometimes changes with time and unfortunately is quite "complicated" due to the nature of ImageMagick. Anyway, I am working on some GitHub Actions to automate the compilation process which I hope to release in the next few days.

To compile the program, in addition to Visual Studio 2022 with the necessary sdks for C and C++, you also need Qt5 (Qt6 is also compatible but at the moment the project is not configured to be compiled with these libraries), the Qt VS Tools for Visual Studio 2022 plugin, and ImageMagick.

The problem is that in order to compile the program properly, you need to configure and compile the ImageMagick libraries manually.

**Comment by lduperval** [comment]
Well, I built ImageMagick and Qt 5 (using these instructions: https://www.qtcentre.org/threads/72011-Qt5-and-Visual-Studion-2022?p=310996).

I can't figure out how to include the builds as dependencies in the project, though. I don't see the "Add Project..." option in the menu of Visual Studio 2022.

**Comment by Faster3ck** [comment]
Hi, you don't need to compile Qt5; only ImageMagick requires compilation. You can use the downloadable version from the Qt site.

Next, you'll need to download the Qt extension for Visual Studio: https://marketplace.visualstudio.com/items?itemName=TheQtCompany.QtVisualStudioTools2022

After downloading, open the .sln file and configure the Qt and ImageMagick directories in the project settings.

However, if you can wait a few days, I'm currently finalizing the workflow using GitHub Actions to compile Converseen on Windows.

I was thinking to drop the support for the .sln project and instead use the .pro project directly. This approach is much more practical and intuitive, especially for compiling the project from the command line.

At the moment the current 'converseen.pro' file is not 100% ready for Windows but, in any case, you could try to compile Converseen using that method without installing the Visual Studio extension!
