### ISSUE TITLE
VirusTotal reports 3 malware detections for Version 0.12.0.1

### ISSUE THREAD

**Issue by jbionic2016** [Faster3ck/Converseen#155]
https://www.virustotal.com/gui/file/4a6e1241435a1528a494a0c73b58414d9243032e6613b3da04a7f4e6850b5104

Is there any way to fix it?

**Comment by Faster3ck** [comment]
Hi, unfortunately, it is common for VirusTotal to report certain ImageMagick modules as false positives. The ImageMagick modules included within the Windows versions of Converseen are compiled via source code and, therefore, are not code-signed. Anyway, I have noticed that even some modules from the official and code-signed releases of ImageMagick are randomly reported as false positives.

Unfortunately, I'm not sure if there is a way to fix this problem. However, I am working on a GitHub Action to compile (including ImageMagick) and deploy Converseen directly through GitHub, ensuring that the entire process is as transparent as possible!

**Comment by Faster3ck** [comment]
Since version **0.12.0.2-2** of Converseen I have been using [ImageMagick's official and codesigned dll libraries](https://imagemagick.org/script/download.php#windows) to compile and deploy the final packages.

The problem of false positives, while still present on some virustotal antiviruses, has been drastically reduced and the entire build and release process can be followed via [GitHub Actions](https://github.com/Faster3ck/Converseen/actions/runs/7508467092).
