### ISSUE TITLE
Converseen 0.12.0.2 windows installer contains virus: Trojan:Win32/OffLoader!pz

### ISSUE THREAD

**Issue by kelemvor4** [Faster3ck/Converseen#158]
Luckily, windows defender is blocking and deleting the file.  You may want to clean up the installer.   Any modern windows 10/11 system should detect and delete it unless the user has completely disabled virus protection.  That should minimize your user impact.

Trojan:Win32/OffLoader.RPY!PZ is a Trojan downloader, which is obvious, that downloads and installs other malware onto compromised systems. It is a Trojan:Win32/OffLoader family member, a known threat to Windows systems. It spreads through various channels, including phishing emails, malicious websites, and compromised USB drives. Once it infiltrates a system, it downloads and installs additional malware, such as ransomware, spyware, and cryptocurrency miners.

Moreover, Trojan:Win32/OffLoader.RPY!PZ is a tool for stealing personal information, including login credentials, credit card numbers, and social security numbers. It can also disable security software and modify system settings. If you suspect your system is infected with Trojan:Win32/OffLoader.RPY!PZ, using a reputable antivirus program to scan your system, is essential. Additionally, it’s worth taking appropriate measures.

I don't need any help myself, I'm just giving you a heads up about a problem.

**Comment by Faster3ck** [comment]
Hi, the problem had already been reported to me a few days ago and I recompiled a second build using the official and codesigned ImageMagick packages and the problem should have been fixed with Converseen 0.12.0.2 build 2 (0.12.0.2-2).

The problem was due to the fact that I was compiling the source code of ImageMagick on my own and some antivirus reported some dlls as false positives. With the official, codesigned version of ImageMagick this problem should have been fixed with most antiviruses.

For a detailed overview of how the ImageMagick source code and Converseen were compiled in this specific build, please refer to the following link:
https://github.com/Faster3ck/Converseen/actions/runs/7452391694

Anyway can you offer me more information about the problem? Could you tell me if the version you encountered the problem with was 0.12.0.2-1 or 0.12.0.2-2? Did you use the installer version or the portable version?

Thank you in advance

**Comment by Faster3ck** [comment]
I thoroughly checked both versions 0.12.0.2-1 and 0.12.0.2-2 of Converseen for Windows, including both Installer and Portable. I found no trace of Trojan:Win32/OffLoader.RPY!PZ.

VirusTotal corrected the detection of some false positives that had been reported by certain antiviruses earlier.

To be honest, I can't figure out the origin of this report. However, the advice I can give is to always verify that the program is downloaded from reliable sources and that the md5sum matches that of the officially released files. You can view them here:
https://sourceforge.net/projects/converseen/files/Converseen/Converseen%200.12/

Also, it would be interesting to understand why user @Ainaemaet reacted negatively to my previous comment. Perhaps he could correct me if I said something incorrect.
