### ISSUE TITLE
Can you return "0.000" in Resolution as the default

### ISSUE THREAD

**Issue by bungadrum** [Faster3ck/Converseen#162]
Can you return the "0.000" for Resolution X-Y as the default. Still having issue with the DPI settings it is set to "96" when you open it and if you try to convert with that default setting it will give you "72" instead. Would it be possible to return that option to how it was in version 0.9.11.1? It was easier when you had to set it yourself this way you just don't know what you will get.

**Comment by bungadrum** [comment]
Before it was the value and then ".000" when you set it can you bring this back if possible
![DPI](https://github.com/Faster3ck/Converseen/assets/75974100/2d4d6ccb-8af9-4f55-9574-bdf103dc2a35)

**Comment by Faster3ck** [comment]
Hi, I was trying to give a default value to the options for resolution but didn't know if these options were better than the previous ones.

In that case I will soon restore the options for resolution as they were previously.

**Comment by bungadrum** [comment]
After latest update the DPI works like it should

**Comment by Faster3ck** [comment]
Great, I'm glad everything is working well now. I had to fix several functions related to resolution, especially regarding PNG files. I'm not sure if the problems were due to IM documentation or if there is actually a bug in the metadata handling of PNG files.

Additionally, the Qt libraries were not displaying the correct resolution of the images on the program screen.

Regardless, the resolution should be set as an integer, so I did not include floating point numbers in the resolution settings!
