### ISSUE TITLE
Output path missing?

### ISSUE THREAD

**Issue by DaveOffiler** [Faster3ck/Converseen#38]
Is it possible to change the path for output converted files? There doesn't appear to be any such option - if there isn't please consider such an option.
 I assume the default is the whatever the input file path is (hence the overwrite setting options). However, whatever the overwrite setting is, or the file type, output images always end up in my home directory - as if the input path is not being appended tto the output file name.
(V0.9.6.2 on OpenSUSE Tumbleweed)

**Comment by Faster3ck** [comment]
In order to change the output directory:

- Scroll down the panel on the left.
- Locate the **Output options** box.
- Click the "..." button next to the "Save in" input box to choose the output directory.
- Make sure the **Image's directory** checkbox is unchecked.

I hope it will help. For any question don't hesitate to ask! :)

**Comment by DaveOffiler** [comment]
Doh!! Completely missed the LH panel scroll-down. Thanks for the quick response - a case of  **Error #0000 : User error - reboot user**
