### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by Dominiquini** [Faster3ck/Converseen#68]
The new version (0.9.8.0) is not opening! I restored anold version (0.9.7.2) and everything is ok!

I using Windows 10 (64 bits)

Thanks

**Comment by Faster3ck** [comment]
Did you received some kind of error messages? Did you downloaded the installer version or the portable version?

**Comment by Dominiquini** [comment]
I didn't receive any error messages. The app just doesn't open ...
I tested with the installer!

**Comment by Dominiquini** [comment]
The portable version have the same problem.
After I try to start the app, one file is created in this directory:

"C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_converseen.exe_4b9ed742c9418ca453de2a69421fb98c3ce2e6bf_cdff7e1f_7aed54e4-1a09-40c7-91e8-4f9a0baf7dbe\Report.wer"

**Comment by Faster3ck** [comment]
Thank you very much for your help! There was a problem with the bundled ImageMagick libraries.
Now the problem should be solved. Please, try to download the new release and let me know if the problem is solved! :)

https://github.com/Faster3ck/Converseen/releases/download/v0.9.8.0/Converseen-0.9.8.0-2-win32-setup.exe

https://github.com/Faster3ck/Converseen/releases/download/v0.9.8.0/Converseen-0.9.8.0-2-win32-setup.exe

**Comment by Dominiquini** [comment]
It worked here!
I will close the issue.

Thanks.
