### ISSUE TITLE
Converseen converts but doesn't save the file

### ISSUE THREAD

**Issue by Djibril57** [Faster3ck/Converseen#74]
I use Converseen from 3 years, before on Linux Ubuntu. Now I have Linux Mint Cinnamon and I have this problem. Converseen tell me that files was been converted but I can't open the destination and it doesn't save anything. Can I do anything to solve this bug?
Thanks

**Comment by Faster3ck** [comment]
Hi,

Please try to check if, in the left column, the **Save in:** box is empty or try to select another folder.
Let me know if the problem is solved.

**Comment by Djibril57** [comment]
Hi Francesco, thank you. Are you Italian?
Anyway I tried what you tell me, but it doesn't work.
I'll send you two screenshots of what's going on on my PC

Il giorno mar 23 giu 2020 alle ore 17:14 Francesco Mondello <
notifications@github.com> ha scritto:

**Comment by alain230** [comment]
Hi,
I have the same problem, just with PDF.
Have you solved the problem and how ? Thank's
Alain

**Comment by Djibril57** [comment]
Hi Alan! Unfortunately I haven't solved the problem yet
I hope that someone will reply

**Comment by Faster3ck** [comment]
Hello,

Finally I found a solution in [this forum](https://askubuntu.com/questions/1081895/trouble-with-batch-conversion-of-png-to-pdf-using-convert). 

In order to convert to PDF and re-enable the Open Destination button, is needed to enable the PDF support in ImageMagick since it was disabled for some security reasons.

There are two ways to do this:

1. **Eliminating all usage restrictions**
    `sudo mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xmlout`
2. **Eliminating only the restriction to combine into PDF**
    Edit the _/etc/ImageMagick-6/policy.xml_ file and change the line:
`<policy domain="coder" rights="none" pattern="PDF" />`
to
`<policy domain="coder" rights="read|write" pattern="PDF" />`

I tested it in Ubuntu and it works perfectly. Let me know if it works!

**Comment by Djibril57** [comment]
Wow! I tryed the first method and... It works!
Thank you so much Francesco!

Il giorno gio 29 ott 2020 alle ore 14:52 Francesco Mondello <
notifications@github.com> ha scritto:

**Comment by Faster3ck** [comment]
That's great, I'm glad it worked! :)
